name: Unit tests
on:
  pull_request:
    paths:
      - 'packages/**'
  push:
    branches:
      - master

jobs:
  test_london:
    name: London time
    runs-on: ubuntu-latest
    steps:
      - name: Checkout âœ…
        uses: actions/checkout@v3
      - name: Set Timezone ğŸŒğŸŒğŸŒ
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: 'Europe/London'
      - name: Setup Node.js ğŸ”§
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies ğŸ› ï¸
        run: npm i
      - name: Run Vitest ğŸ§ª
        run: npx vitest run --silent

  test_mountain_view:
    name: Mountain View time
    runs-on: ubuntu-latest
    steps:
      - name: Checkout âœ…
        uses: actions/checkout@v3
      - name: Set Timezone ğŸŒğŸŒğŸŒ
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: 'US/Pacific'
      - name: Setup Node.js ğŸ”§
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies ğŸ› ï¸
        run: npm i
      - name: Run Vitest ğŸ§ª
        run: npx vitest run --silent

  test_tokyo:
    name: Tokyo time
    runs-on: ubuntu-latest
    steps:
      - name: Checkout âœ…
        uses: actions/checkout@v3
      - name: Set Timezone ğŸŒğŸŒğŸŒ
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: 'Asia/Tokyo'
      - name: Setup Node.js ğŸ”§
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies ğŸ› ï¸
        run: npm i
      - name: Run Vitest ğŸ§ª
        run: npx vitest run --silent
